// Caption generator with funny, clean captions for 16-35 audience
const captionTemplates = [
  "When you finally understand the instructions",
  "Me pretending to know what's happening",
  "POV: You're the main character",
  "Nobody: ... Absolutely nobody: ...",
  "This could be us but you playing",
  "When the wifi drops to one bar",
  "Expectation vs Reality",
  "My last two brain cells fighting",
  "How it started vs How it's going",
  "Plot twist:",
  "Wait for it...",
  "I didn't sign up for this",
  "Is this... happiness?",
  "Nailed it",
  "Task failed successfully",
  "Outstanding move",
  "He's speaking the language of gods",
  "Carefully, he's a hero",
  "What can I say except you're welcome",
  "This is fine",
  "I'm in danger",
  "That's a lot of damage",
  "You weren't supposed to do that",
  "I see this as an absolute win",
  "Reality can be whatever I want",
  "The hardest choices require the strongest wills",
  "I am inevitable",
  "I'm something of a scientist myself",
  "With great power comes great electricity bill",
  "I missed the part where that's my problem",
  "You and I are not so different",
  "I'm gonna put some dirt in your eye",
  "Pizza time",
  "Day 1 of quarantine vs Day 100",
  "Me vs My responsibilities",
  "Monday morning energy",
  "Friday afternoon vibes",
  "When your code actually works",
  "Debugging at 3am be like",
  "My brain during exams",
  "Adults trying to be cool",
  "Pretending I have my life together",
  "Instant regret",
  "Hold my drink",
  "What did I just witness",
  "This is chaos",
  "Improvise. Adapt. Overcome.",
  "Modern problems require modern solutions",
  "Work smarter not harder",
  "I'm about to end this man's whole career",
  "Why are you booing me? I'm right",
  "I don't need sleep I need answers",
  "Look how they massacred my boy",
  "You're telling me a shrimp fried this rice?",
  "Corporate needs you to find the difference",
  "They're the same picture",
  "Sometimes my genius is almost frightening",
  "You guys are getting paid?",
  "I've won but at what cost",
  "The risk I took was calculated but man am I bad at math",
  "This is getting out of hand",
  "A surprise to be sure but a welcome one",
  "Hello there",
  "I have the high ground",
  "This is where the fun begins",
  "Another happy landing",
  "Not the hero we deserved but the hero we needed",
  "Because that's what heroes do",
  "I could do this all day",
  "This does put a smile on my face",
  "The ability to speak does not make you intelligent",
  "I'm just a simple man trying to make my way",
  "Your scientists were so preoccupied with whether they could that they didn't stop to think if they should",
  "Life finds a way",
  "Well that was unexpected",
  "Ladies and gentlemen we got him",
  "Mission accomplished",
  "Suffering from success",
  "You played yourself",
  "Congratulations you played yourself",
  "Why would you say something so controversial yet so brave",
  "They had us in the first half not gonna lie",
  "You're not wrong you're just an idiot",
  "That's just science",
  "It's big brain time",
  "This is beyond science",
  "Visible confusion",
  "Confused screaming",
  "Angry noises",
  "Sad noises",
  "Happy noises",
  "Excited noises",
  "The trickster",
  "Illusion 100",
  "Sneak 100",
  "Speech 100",
  "Destruction 100",
  "When you're trying your best but it's not enough",
  "Quality content right here"
];

function generateCaptions(count) {
  const captions = [];
  const shuffled = [...captionTemplates].sort(() => Math.random() - 0.5);
  
  for (let i = 0; i < count; i++) {
    captions.push({
      id: `caption_${Date.now()}_${i}_${Math.random().toString(36).substr(2, 9)}`,
      text: shuffled[i % shuffled.length]
    });
  }
  
  return captions;
}

module.exports = { generateCaptions };
